### ISSUE TITLE
Uncaught (in promise) Error: Could not get translation for locale pt.

### ISSUE THREAD

**Issue by lipecss** [dargmuesli/nuxt-cookie-control#82]
### Environment

yarn add -D @dargmuesli/nuxt-cookie-control

### Reproduction

```js        
<CookieControl locale="pt"/>```

### Describe the bug

```js        
       Uncaught (in promise) Error: Could not get translation for locale pt.
    at Proxy.resolveTranslatable (methods.mjs?v=f59448ea:19:11)
    at CookieControl.vue:399:54
    at renderList (chunk-X4BLWDOR.js?v=f59448ea:3907:16)
    at CookieControl.vue:391:35
    at renderList (chunk-X4BLWDOR.js?v=f59448ea:3925:18)
    at CookieControl.vue:372:21
    at Proxy.renderFnWithContext (chunk-X4BLWDOR.js?v=f59448ea:2140:13)
    at Proxy.<anonymous> (chunk-X4BLWDOR.js?v=f59448ea:3115:79)
    at renderComponentRoot (chunk-X4BLWDOR.js?v=f59448ea:2172:39)
    at ReactiveEffect.componentUpdateFn [as fn] (chunk-X4BLWDOR.js?v=f59448ea:6173:26```

### Additional context

_No response_

### Logs

_No response_

**Comment by dargmuesli** [comment]
Please follow the given bug report template: a [minimal reproduction](https://stackblitz.com/github/dargmuesli/nuxt-cookie-control?file=playground%2Fapp.vue) allows us to help you quickly!
